In [1]:
import torch
import torch.nn as nn
import numpy as np
import os

In [ ]:
'''
to do: train one to get scale (std)
    get the intended std outputs
    map each to an input
    train.

train both and get the output into a matrix.
'''

In [2]:
ALL_PHONEMES =['aa', 'ae', 'ah', 'ao', 'aw', 'ax', 'ax-h', 'axr', 'ay', 'b', 'bcl', 'ch', 'd', 'dcl', 'dh', 'dx', 'eh', 'el', 'em', 'en', 'eng', 'epi', 'er', 'ey', 'f', 'g', 'gcl', 'h#', 'hh', 'hv', 'ih', 'ix', 'iy', 'jh', 'k', 'kcl', 'l', 'm', 'n', 'ng', 'nx', 'ow', 'oy', 'p', 'pau', 'pcl', 'q', 'r', 's', 'sh', 't', 'tcl', 'th', 'uh', 'uw', 'ux', 'v', 'w', 'y', 'z', 'zh']

In [3]:
predictions_folder = "saved_variables/average_and_std_phoneme_feature/"

In [4]:
# load dataset

phonemes = []
scales = []
shifts = []

for indx in range(len(ALL_PHONEMES)):
    phoneme_tensor = np.zeros(len(ALL_PHONEMES))
    phoneme_tensor[indx] = 1
    scale_file = predictions_folder+ALL_PHONEMES[indx]+"_std.txt"
    shift_file = predictions_folder+ALL_PHONEMES[indx]+"_average.txt"
    if os.path.isfile(scale_file):
        scales.append(np.loadtxt(scale_file)[:65])
        shifts.append(np.loadtxt(shift_file)[:65])
        phonemes.append(phoneme_tensor)
#         print(ALL_PHONEMES[indx])
        
phonemes = np.array(phonemes)
scales = np.array(scales)
shifts = np.array(shifts)

phonemes = torch.from_numpy(phonemes).float()
scales = torch.from_numpy(scales).float()
shifts = torch.from_numpy(shifts).float()

In [17]:
losses = []
scale_model = nn.Sequential()
scale_model.add_module("dense1", nn.Linear(61, 65))
scale_model.add_module("act1", nn.ReLU())

# loss_fn = nn.CrossEntropyLoss()
loss_fn = nn.MSELoss()

optimizer_scales = torch.optim.Adam(scale_model.parameters(), lr=0.03)

num_epochs = 1000

for epoch in range(num_epochs):
    scales_pred = scale_model(phonemes)
    loss_scale = loss_fn(scales_pred,scales)
    losses.append(loss_scale)
    print(f"epoch: {epoch}, loss: {loss_scale}")
    optimizer_scales.zero_grad()
    loss_scale.backward()
    optimizer_scales.step()
    if len(losses)>10:
        if losses[-1]>=losses[-10] or losses[-1]>=losses[-5]:
            print("detecting minimum validation loss. stopping early")
            break

epoch: 0, loss: 8.528923034667969
epoch: 1, loss: 8.359004974365234
epoch: 2, loss: 8.16179370880127
epoch: 3, loss: 7.9407219886779785
epoch: 4, loss: 7.698099613189697
epoch: 5, loss: 7.439396858215332
epoch: 6, loss: 7.16878080368042
epoch: 7, loss: 6.889107704162598
epoch: 8, loss: 6.603863716125488
epoch: 9, loss: 6.317841053009033
epoch: 10, loss: 6.03481912612915
epoch: 11, loss: 5.756733417510986
epoch: 12, loss: 5.484508514404297
epoch: 13, loss: 5.218817710876465
epoch: 14, loss: 4.960161209106445
epoch: 15, loss: 4.708911895751953
epoch: 16, loss: 4.465351581573486
epoch: 17, loss: 4.229684352874756
epoch: 18, loss: 4.0020551681518555
epoch: 19, loss: 3.7825558185577393
epoch: 20, loss: 3.571237087249756
epoch: 21, loss: 3.3681118488311768
epoch: 22, loss: 3.1731605529785156
epoch: 23, loss: 2.9863343238830566
epoch: 24, loss: 2.8075592517852783
epoch: 25, loss: 2.6367380619049072
epoch: 26, loss: 2.473752737045288
epoch: 27, loss: 2.318467140197754
epoch: 28, loss: 2.170727

epoch: 450, loss: 3.1558132843056974e-13
epoch: 451, loss: 3.125850544117431e-13
epoch: 452, loss: 3.0994716342103157e-13
epoch: 453, loss: 3.081694513289157e-13
epoch: 454, loss: 3.065064478266488e-13
epoch: 455, loss: 3.0387573967533e-13
epoch: 456, loss: 3.016966288339057e-13
epoch: 457, loss: 3.0027732687495923e-13
epoch: 458, loss: 3.0027732687495923e-13
epoch: 459, loss: 2.984315268864113e-13
epoch: 460, loss: 2.980731167532419e-13
epoch: 461, loss: 2.9688320486893904e-13
epoch: 462, loss: 2.9674342410385135e-13
epoch: 463, loss: 2.9542807002819194e-13
epoch: 464, loss: 2.9541733642668433e-13
epoch: 465, loss: 2.943743610418076e-13
epoch: 466, loss: 2.9436360033524567e-13
epoch: 467, loss: 2.9310560055451074e-13
epoch: 468, loss: 2.9310560055451074e-13
epoch: 469, loss: 2.9247481173055867e-13
epoch: 470, loss: 2.923637081129332e-13
epoch: 471, loss: 2.918476007737758e-13
epoch: 472, loss: 2.9174723075765796e-13
epoch: 473, loss: 2.9121678484476943e-13
epoch: 474, loss: 2.91005338

epoch: 661, loss: 2.35964703722627e-13
epoch: 662, loss: 2.3570663650052115e-13
epoch: 663, loss: 2.354629349572007e-13
epoch: 664, loss: 2.351045248240313e-13
epoch: 665, loss: 2.350328319553757e-13
epoch: 666, loss: 2.3468876039593745e-13
epoch: 667, loss: 2.3431603879409124e-13
epoch: 668, loss: 2.34129664440641e-13
epoch: 669, loss: 2.340866487194476e-13
epoch: 670, loss: 2.3397196723465297e-13
epoch: 671, loss: 2.33699561438816e-13
epoch: 672, loss: 2.331404383784652e-13
epoch: 673, loss: 2.330687726148639e-13
epoch: 674, loss: 2.3266734676050116e-13
epoch: 675, loss: 2.325526652757065e-13
epoch: 676, loss: 2.3215123942134375e-13
epoch: 677, loss: 2.318358450093677e-13
epoch: 678, loss: 2.3170682495084194e-13
epoch: 679, loss: 2.311046861692978e-13
epoch: 680, loss: 2.308036303310529e-13
epoch: 681, loss: 2.306029174038715e-13
epoch: 682, loss: 2.3033053871308884e-13
epoch: 683, loss: 2.300868100647141e-13
epoch: 684, loss: 2.298574470951248e-13
epoch: 685, loss: 2.291262882550549

In [18]:
torch.save({"model":scale_model.state_dict(), "optimizer":optimizer_scales.state_dict()}, "scales_model")

In [25]:
losses = []
shift_model = nn.Sequential()
shift_model.add_module("dense1", nn.Linear(61, 65))
shift_model.add_module("act1", nn.ReLU())

# loss_fn = nn.CrossEntropyLoss()
loss_fn = nn.MSELoss()

# optimizer_shifts = torch.optim.Adam(shift_model.parameters(), lr=0.03)
optimizer_shifts = torch.optim.SGD(shift_model.parameters(), lr=0.6)

num_epochs = 1000

for epoch in range(num_epochs):
    shifts_pred = shift_model(phonemes)
    loss_shift = loss_fn(shifts_pred,shifts)
    losses.append(loss_shift)
    print(f"epoch: {epoch}, loss: {loss_shift}")
    optimizer_shifts.zero_grad()
    loss_shift.backward()
    optimizer_shifts.step()
    
    if len(losses)>10:
        if losses[-1]-losses[-5]>=0:
            print("detecting minimum validation loss. stopping early")
            break

epoch: 0, loss: 51.087947845458984
epoch: 1, loss: 50.6282958984375
epoch: 2, loss: 50.53646469116211
epoch: 3, loss: 50.51144790649414
epoch: 4, loss: 50.50442886352539
epoch: 5, loss: 50.50135803222656
epoch: 6, loss: 50.49980926513672
epoch: 7, loss: 50.498809814453125
epoch: 8, loss: 50.498199462890625
epoch: 9, loss: 50.49785614013672
epoch: 10, loss: 50.49760055541992
epoch: 11, loss: 50.49739456176758
epoch: 12, loss: 50.49721145629883
epoch: 13, loss: 50.49703598022461
epoch: 14, loss: 50.496891021728516
epoch: 15, loss: 50.49678039550781
epoch: 16, loss: 50.496673583984375
epoch: 17, loss: 50.496585845947266
epoch: 18, loss: 50.496524810791016
epoch: 19, loss: 50.4964599609375
epoch: 20, loss: 50.49639892578125
epoch: 21, loss: 50.4963264465332
epoch: 22, loss: 50.496273040771484
epoch: 23, loss: 50.49620819091797
epoch: 24, loss: 50.49614715576172
epoch: 25, loss: 50.49607849121094
epoch: 26, loss: 50.49601745605469
epoch: 27, loss: 50.49595642089844
epoch: 28, loss: 50.49589

epoch: 293, loss: 50.487186431884766
epoch: 294, loss: 50.487159729003906
epoch: 295, loss: 50.48713684082031
epoch: 296, loss: 50.48711395263672
epoch: 297, loss: 50.48709487915039
epoch: 298, loss: 50.4870719909668
epoch: 299, loss: 50.4870491027832
epoch: 300, loss: 50.48702621459961
epoch: 301, loss: 50.48700714111328
epoch: 302, loss: 50.48698806762695
epoch: 303, loss: 50.486968994140625
epoch: 304, loss: 50.486942291259766
epoch: 305, loss: 50.48691940307617
epoch: 306, loss: 50.486907958984375
epoch: 307, loss: 50.486881256103516
epoch: 308, loss: 50.48685836791992
epoch: 309, loss: 50.486839294433594
epoch: 310, loss: 50.48681640625
epoch: 311, loss: 50.48679733276367
epoch: 312, loss: 50.48677062988281
epoch: 313, loss: 50.48674774169922
epoch: 314, loss: 50.486724853515625
epoch: 315, loss: 50.4867057800293
epoch: 316, loss: 50.4866828918457
epoch: 317, loss: 50.486663818359375
epoch: 318, loss: 50.48664474487305
epoch: 319, loss: 50.48662185668945
epoch: 320, loss: 50.48659

epoch: 542, loss: 50.482479095458984
epoch: 543, loss: 50.482452392578125
epoch: 544, loss: 50.48244094848633
epoch: 545, loss: 50.482418060302734
epoch: 546, loss: 50.4824104309082
epoch: 547, loss: 50.482391357421875
epoch: 548, loss: 50.48237228393555
epoch: 549, loss: 50.482357025146484
epoch: 550, loss: 50.482337951660156
epoch: 551, loss: 50.48233413696289
epoch: 552, loss: 50.48231887817383
epoch: 553, loss: 50.48229217529297
epoch: 554, loss: 50.48227310180664
epoch: 555, loss: 50.48225784301758
epoch: 556, loss: 50.482242584228516
epoch: 557, loss: 50.48221969604492
epoch: 558, loss: 50.48221206665039
epoch: 559, loss: 50.482208251953125
epoch: 560, loss: 50.482181549072266
epoch: 561, loss: 50.4821662902832
epoch: 562, loss: 50.48215103149414
epoch: 563, loss: 50.48212432861328
epoch: 564, loss: 50.482112884521484
epoch: 565, loss: 50.48209762573242
epoch: 566, loss: 50.482086181640625
epoch: 567, loss: 50.48206329345703
epoch: 568, loss: 50.48204040527344
epoch: 569, loss: 5

epoch: 896, loss: 50.477378845214844
epoch: 897, loss: 50.47735595703125
epoch: 898, loss: 50.47733688354492
epoch: 899, loss: 50.47733688354492
epoch: 900, loss: 50.477333068847656
epoch: 901, loss: 50.47731018066406
epoch: 902, loss: 50.4773063659668
epoch: 903, loss: 50.477298736572266
epoch: 904, loss: 50.47727584838867
epoch: 905, loss: 50.477264404296875
epoch: 906, loss: 50.477237701416016
epoch: 907, loss: 50.477237701416016
epoch: 908, loss: 50.47721862792969
epoch: 909, loss: 50.47720718383789
epoch: 910, loss: 50.47721481323242
epoch: 911, loss: 50.4771842956543
epoch: 912, loss: 50.47716522216797
epoch: 913, loss: 50.47716522216797
epoch: 914, loss: 50.477134704589844
epoch: 915, loss: 50.47713088989258
epoch: 916, loss: 50.47713851928711
epoch: 917, loss: 50.47711181640625
epoch: 918, loss: 50.47709274291992
epoch: 919, loss: 50.47708511352539
epoch: 920, loss: 50.477073669433594
epoch: 921, loss: 50.47705078125
epoch: 922, loss: 50.47704315185547
epoch: 923, loss: 50.4770

In [14]:
shifts_pred

tensor([[0.0000, 0.0000, 0.4293,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.6109,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.7154,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.4282,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.4941,  ..., 0.0000, 0.0000, 0.0000]],
       grad_fn=<ReluBackward0>)

In [15]:
shifts

tensor([[ -2.8344,  -0.4313,   0.4293,  ..., -11.9093, -15.0479, -18.3271],
        [ -2.6625,  -0.2299,   0.6109,  ..., -11.3789, -14.4855, -17.8279],
        [ -2.7991,  -0.2632,   0.7154,  ..., -11.4353, -14.5021, -17.8652],
        ...,
        [ -3.2440,  -0.6030,   0.4282,  ..., -11.7126, -14.7787, -18.1606],
        [ -3.7102,  -1.3226,  -0.3567,  ...,  -8.7786, -11.7740, -15.0684],
        [ -2.8030,  -0.3818,   0.4941,  ...,  -9.4130, -12.5467, -15.8897]])

In [ ]:
def zmuv_normalize_phoneme_class(feature_matrix, calculate_mean_and_std=True, phoneme_mean=None, phoneme_std=None):
    '''
    return the normalized feature class of matrix phoneme_class_features_matrix, the mean and standard deviations
    inputs:
        feature_matrix (np.array): a 2d feature matrix of various instances of a phoneme. The phonemes instances are stacked on the z (?) axis
        calculate_mean_and_std (bool): whether to calculate mean and std or not. should be false if inputting values for phoneme_mean and phoneme_std
        phoneme_mean (np.array):  the average feature
        phoneme_std (np.array):  the standard deviation of features
        
    returns:
        normalized_features (np.array): the normalized feature matrix 
        phoneme_mean (np.array):  the average feature
        phoneme_std (np.array):  the standard deviation of features
    '''
    if calculate_mean_and_std:
        phoneme_mean, phoneme_std = np.mean(feature_matrix,0),np.std(feature_matrix,0)
    normalized_features = (feature_matrix - phoneme_mean)/(phoneme_std)
    
    return normalized_features, phoneme_mean, phoneme_std

In [ ]:
def get_phonemes_from_single_file(filename):
    '''
    this returns a dicitonary mapping phoneme names to numpy 1-D matrices of features of the phoneme class of a particular length (padded with nans if data is less than) found in a file
    inputs:
        filename (str): the input file
        
    '''
    output_dictionary = {}
    f = open(filename, "r")
    lines = f.readlines()
    
    f.close()
    for line in lines: 
        line = line.split()
        current_phoneme = line[-1]
        line = line[:-1]
        line = np.array(line,dtype="float64")
        if current_phoneme in output_dictionary:
            output_dictionary[current_phoneme].append(line)
        else:
            output_dictionary[current_phoneme] = [line]
        
    return output_dictionary

In [ ]:
# testing above function
TEST_FILE = 'Y:/personal/ojuba.mezisashe/Sentences/TIMIT_dp/output/TRAIN/DR1/FCJF0/SI648.txt'
print(TEST_FILE)
phonemes_from_file = get_phonemes_from_single_file(TEST_FILE)
# _ = get_phonemes_from_single_file(filename, 100) # edge case test

In [ ]:
phoneme = "aa"
phonemes_from_file[phoneme][0]

In [ ]:
a = np.array([1,2,3,4])
d = np.diag(a)

In [29]:
a = np.array([1,2,3,4])

In [30]:
a*a+a

array([ 2,  6, 12, 20])